# Form implementation generated from reading ui file 'email_view.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 414)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sender_label = QtWidgets.QLabel(parent=self.groupBox)
        self.sender_label.setObjectName("sender_label")
        self.horizontalLayout.addWidget(self.sender_label)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reciever_label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.reciever_label.setObjectName("reciever_label")
        self.horizontalLayout_2.addWidget(self.reciever_label)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title_label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout_3.addWidget(self.title_label)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.content_label = QtWidgets.QLabel(parent=self.groupBox_4)
        self.content_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.content_label.setObjectName("content_label")
        self.horizontalLayout_4.addWidget(self.content_label)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.close_button = QtWidgets.QPushButton(parent=Form)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_5.addWidget(self.close_button)
        self.answer_button = QtWidgets.QPushButton(parent=Form)
        self.answer_button.setObjectName("answer_button")
        self.horizontalLayout_5.addWidget(self.answer_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(3, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Отправитель"))
        self.sender_label.setText(_translate("Form", "sender"))
        self.groupBox_2.setTitle(_translate("Form", "Получатель"))
        self.reciever_label.setText(_translate("Form", "recipient"))
        self.groupBox_3.setTitle(_translate("Form", "Заголовок"))
        self.title_label.setText(_translate("Form", "title"))
        self.groupBox_4.setTitle(_translate("Form", "Содержание"))
        self.content_label.setText(_translate("Form", "Content"))
        self.close_button.setText(_translate("Form", "Закрыть"))
        self.answer_button.setText(_translate("Form", "Ответить"))
