# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 384)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imgLayout = QtWidgets.QHBoxLayout()
        self.imgLayout.setObjectName("imgLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.imgLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.imgLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.imgLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.username_edit = QtWidgets.QLineEdit(parent=Form)
        self.username_edit.setObjectName("username_edit")
        self.horizontalLayout.addWidget(self.username_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.password_edit = QtWidgets.QLineEdit(parent=Form)
        self.password_edit.setObjectName("password_edit")
        self.horizontalLayout_2.addWidget(self.password_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.back_button = QtWidgets.QPushButton(parent=Form)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_3.addWidget(self.back_button)
        self.login_button = QtWidgets.QPushButton(parent=Form)
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_3.addWidget(self.login_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Имя аккаунта"))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.back_button.setText(_translate("Form", "Назад"))
        self.login_button.setText(_translate("Form", "Войти"))
